# Playbook for installing the EESSI compatibility layer.
---
- name: Install compatibility layer
  hosts: localhost
  connection: local
  environment:
    PATH:
      "{{ gentoo_prefix_path }}/usr/sbin\
      :{{ gentoo_prefix_path }}/usr/bin\
      :{{ gentoo_prefix_path }}/sbin\
      :{{ gentoo_prefix_path }}/bin\
      :{{ ansible_env.PATH }}"
    EPREFIX: "{{ gentoo_prefix_path }}"
    BPREFIX: "{{ gentoo_prefix_path }}"
    LC_ALL: C
  roles:
    - compatibility_layer
  become: true

# original (different setting for hosts & no connection)
#  hosts: cvmfsstratum0servers
