# Playbook for installing the EESSI compatibility layer.
---
- name: Install compatibility layer
  hosts: cvmfsstratum0servers
  environment:
    PATH:
       "{{ gentoo_prefix_path }}/usr/sbin\
       :{{ gentoo_prefix_path }}/usr/bin\
       :{{ gentoo_prefix_path }}/sbin\
       :{{ gentoo_prefix_path }}/bin\
       :{{ ansible_env.PATH }}"
    EPREFIX: "{{ gentoo_prefix_path }}"
    BPREFIX: "{{ gentoo_prefix_path }}"
    LC_ALL: C
  roles:
    - compatibility_layer
  become: True
